apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: hozza/ambulance-ufe
  newName: hozza/ambulance-ufe
  newTag: 1.1.0
- name: hozza/ambulance-wl-webapi
  newName: hozza/ambulance-wl-webapi
  newTag: 1.1.0
- name: hozza/reserver-ufe
  newName: hozza/reserver-ufe
  newTag: 1.1.0
- name: hozza/reserver-webapi
  newName: hozza/reserver-webapi
  newTag: 1.1.0

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: hozza-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  hozza-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: reserver-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  reserver-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1